# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e52281df56af6e9d22092df8399cea414a84e4a1469be651b43beec92e7c82d8e0d474151f78b423ef5de808800e0fcd10287bc2ba28ae5dadfdc1e914533c6

test:
  secret_key_base: 0a8439a192a773146ea0898f5d3b6ae47f286653512d8c7be63c52b3a0bb0d0514fef3a8310f1e0d68831bef9c4e7bb07c59382375d776512e8a018e0a191b8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
